### ISSUE TITLE
How to install Pytorch Rocm 5.4.2?

### ISSUE THREAD

**Issue by rquercia** [fepegar/SlicerPyTorch#15]
Hello, 
can you explain me how I can install Pytorch Rocm 5.4.2 (pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.4.2)

Thanks in advance

**Comment by lassoan** [comment]
After installing PyTorch extension, go to `PyTorch Utils` module, click `show all compatible` button and if your computer is detected to be compatible with ROCm then it will be available then you can select it in the list.

**Comment by fepegar** [comment]
@rquercia were you able to install what you needed?

**Comment by rquercia** [comment]
Sorry for the delay,

i can install it manually using pip_install('torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.4.2') from the python console.

Thank you, please close the issue if you consider it.

**Comment by lassoan** [comment]
@rquercia Installing pytorch in Slicer using `pip_install` is not a viable option if you want to publish your extension, because you need to ensure that pytorch installation is correct on all operating system, hardware (CPU only, NVIDIA GPU, AMD GPU), installed driver and SDK version combinations (see https://pytorch.org/get-started/locally/). If you hardcode a specific pip install command then it will work on a few configurations and fail on all others. SlicerPyTorch extension uses LightTheTorch Python package to automatically determine the correct pytorch installation URL. If you have run into any problem then you can report here or to LightTheTorch maintainers.
